# -*- coding: utf-8 -*-
"""UAE_Covid19_DAG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kOE1rFDXn0ySF8o0YQdBTd38LPqqdL-l
"""

import datetime as dt
from datetime import timedelta
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.python_operator import PythonOperator


def Get_DF_i(Day):
        import pandas as pd
        DF_i=None
        try: 
            URL_Day=f'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{Day}.csv'
            DF_day=pd.read_csv(URL_Day)
            DF_day['Day']=Day
            cond=(DF_day.Country_Region=='United Arab Emirates')
            Selec_columns=['Day','Country_Region', 'Last_Update',
                  'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
                  'Combined_Key', 'Incident_Rate', 'Case_Fatality_Ratio']
            DF_i=DF_day[cond][Selec_columns].reset_index(drop=True)
        except:
            print(f'{Day} is not available!')
            pass
        return DF_i

def Create_data():
        import pandas as pd
        List_of_Days=[]
        import datetime
        format = "%Y-%m-%d"
        dt_string = "2021-1-1"
        d=datetime.datetime.today() -datetime.datetime.strptime(dt_string, format)
        for i in range(0,366):
                Previous_Date = datetime.datetime.today() - datetime.timedelta(days=d.days-i)
                if (Previous_Date > datetime.datetime.today()):
                  break
                if (Previous_Date.day >9):
                    if (Previous_Date.month >9):
                          List_of_Days.append(f'{Previous_Date.month}-{Previous_Date.day}-{Previous_Date.year}')
                    else:
                          List_of_Days.append(f'0{Previous_Date.month}-{Previous_Date.day}-{Previous_Date.year}')
                else:
                    if (Previous_Date.month >9):
                          List_of_Days.append(f'{Previous_Date.month}-0{Previous_Date.day}-{Previous_Date.year}')
                    else:
                          List_of_Days.append(f'0{Previous_Date.month}-0{Previous_Date.day}-{Previous_Date.year}')
            
        DF_all=[]
        for Day in List_of_Days:
            DF_all.append(Get_DF_i(Day))
            
        DF_UAE=pd.concat(DF_all).reset_index(drop=True)
        DF_UAE['Last_Update']=pd.to_datetime(DF_UAE.Last_Update, infer_datetime_format=True)  
        DF_UAE['Day']=pd.to_datetime(DF_UAE.Day, infer_datetime_format=True)  
        DF_UAE['Case_Fatality_Ratio']=DF_UAE['Case_Fatality_Ratio'].astype(float)
        DF_UAE.set_index('Day', inplace=True)
        DF_UAE.to_csv('/opt/airflow/data/DF_UAE.csv')
        DF_UAE.to_csv('/opt/airflow/output/UAE_Scorning_Report.csv')

def MinMaxScaler():
        import pandas as pd
        from sklearn.preprocessing import MinMaxScaler
        DF_UAE = pd.read_csv('/opt/airflow/data/DF_UAE.csv', parse_dates=['Last_Update'])
        DF_UAE['Day']=DF_UAE.Day
        DF_UAE.set_index('Day', inplace=True)
        min_max_scaler = MinMaxScaler()
        DF_UAE_u=DF_UAE.copy()
        Select_Columns=['Confirmed','Deaths', 'Recovered', 'Active','Case_Fatality_Ratio']
        DF_UAE_u_2=DF_UAE_u[Select_Columns]
        DF_UAE_u_3 = pd.DataFrame(min_max_scaler.fit_transform(DF_UAE_u_2[Select_Columns]),columns=Select_Columns)
        DF_UAE_u_3['Day']=DF_UAE_u.index
        DF_UAE_u_3.set_index('Day', inplace=True)
        DF_UAE_u_3.to_csv('/opt/airflow/data/DF_UAE_Scaled.csv')
        

def Plotting():
        import pandas as pd 
        import matplotlib.pyplot as plt
        DF_UAE_u_3 = pd.read_csv('/opt/airflow/data/DF_UAE_Scaled.csv', parse_dates=['Day'])
        DF_UAE_u_3.set_index('Day', inplace=True) 
        Select_Columns=['Confirmed','Deaths', 'Recovered', 'Active','Case_Fatality_Ratio']
        DF_UAE_u_3[Select_Columns].plot(figsize=(30,20))
        plt.savefig('/opt/airflow/output/UAE_Scoring_Report.png')
    

def CSV_to_Postgres():
        import sqlalchemy
        from sqlalchemy import create_engine
        import pandas as pd

        DF_UAE_Scaled = pd.read_csv('/opt/airflow/data/DF_UAE_Scaled.csv', parse_dates=['Day'])
        DF_UAE_Scaled.set_index('Day', inplace=True)

        host="postgres"
        database="airflow"
        user="airflow"
        password="airflow"
        port='5432'
        engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')
        DF_UAE_Scaled.to_sql('Covid19_Scaled', engine,if_exists='replace',index=False)    

 
 
default_args = {
    'owner': 'admin',
    'start_date': dt.datetime(2021, 5, 24),
    'retries': 1,
    'retry_delay': dt.timedelta(minutes=1),
}
 
with DAG('Covid19_UAE_DAG',
         default_args=default_args,
         schedule_interval=timedelta(days=1),  
         catchup=False,     
         ) as dag:
    Install_dependecies = BashOperator(task_id='installing_packages',bash_command='pip install sklearn matplotlib')
    Extract_Data = PythonOperator(task_id='Extract_Covid_Data', python_callable=Create_data)
    Data_Scaling = PythonOperator(task_id='Scale_the_Data_for_UAE', python_callable=MinMaxScaler)
    Plot= PythonOperator(task_id='Plot_UAE_Covid_Situation', python_callable=Plotting)
    Push_to_Postgres = PythonOperator(task_id='Load_to_PostGres', python_callable=CSV_to_Postgres)

Install_dependecies >> Extract_Data >> Data_Scaling >> Plot >> Push_to_Postgres